### ISSUE TITLE
When i run the example tran_imagenet_resnet.py by pytorch, dist.broadcast: RuntimeError: Tensors must be contiguous

### ISSUE THREAD

**Issue by JLtwoP** [gpauloski/kfac_pytorch#31]

**Comment by JLtwoP** [comment]
my pytorch version is 1.2.0

**Comment by gpauloski** [comment]
I have seen and fixed this issue before; however, it seems the fix did not make it into the last commit. ab06e72c29abdd9e65f063b8d987b262e1d40a30 should resolve it but feel free to reopen the issue if it persists.

**Comment by JLtwoP** [comment]
> I have seen and fixed this issue before; however, it seems the fix did not make it into the last commit. [ab06e72](https://github.com/gpauloski/kfac_pytorch/commit/ab06e72c29abdd9e65f063b8d987b262e1d40a30) should resolve it but feel free to reopen the issue if it persists.

thanks, i will try it
